# Generated by Django 5.2.10 on 2026-01-27 00:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(max_length=20, verbose_name='原阶段')),
                ('to_stage', models.CharField(max_length=20, verbose_name='新阶段')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='持续天数')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='opportunities.opportunity', verbose_name='商机')),
            ],
            options={
                'verbose_name': '阶段历史',
                'verbose_name_plural': '阶段历史',
                'db_table': 'core_stagehistory',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('call', '电话'), ('email', '邮件'), ('meeting', '会议'), ('visit', '拜访'), ('demo', '演示'), ('proposal', '方案'), ('contract', '合同'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类型')),
                ('direction', models.CharField(blank=True, choices=[('outbound', '外呼'), ('inbound', '接入')], max_length=20, null=True, verbose_name='方向')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('outcome', models.TextField(blank=True, null=True, verbose_name='结果')),
                ('activity_date', models.DateTimeField(verbose_name='活动日期')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
                ('next_action', models.CharField(blank=True, max_length=200, null=True, verbose_name='后续行动')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='后续行动日期')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customers.contact', verbose_name='联系人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='opportunities.opportunity', verbose_name='商机')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_activities', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'core_activity',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['customer', 'activity_date'], name='core_activi_custome_c49464_idx'), models.Index(fields=['owner', 'activity_date'], name='core_activi_owner_i_f70cd7_idx'), models.Index(fields=['type'], name='core_activi_type_a833fb_idx'), models.Index(fields=['direction'], name='core_activi_directi_fd3363_idx'), models.Index(fields=['activity_date'], name='core_activi_activit_0ff4f4_idx'), models.Index(fields=['next_action_date'], name='core_activi_next_ac_612d08_idx')],
            },
        ),
    ]
