# Generated by Django 5.2.10 on 2026-01-27 00:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('feishu_tenant_key', models.CharField(max_length=100, unique=True, verbose_name='飞书租户Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('settings', models.JSONField(default=dict, verbose_name='企业配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '企业账号',
                'verbose_name_plural': '企业账号',
                'db_table': 'accounts_account',
                'indexes': [models.Index(fields=['feishu_tenant_key'], name='accounts_ac_feishu__140357_idx'), models.Index(fields=['is_active'], name='accounts_ac_is_acti_b52bc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feishu_open_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='飞书OpenID')),
                ('feishu_union_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='飞书UnionID')),
                ('feishu_user_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='飞书UserID')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('department_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门ID')),
                ('department_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='部门名称')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('feishu_team_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='飞书团队ID')),
                ('role', models.CharField(choices=[('admin', '系统管理员'), ('sales_manager', '销售经理'), ('sales', '销售人员'), ('presales', '售前支持'), ('aftersales', '售后支持'), ('viewer', '只读用户')], default='sales', max_length=20, verbose_name='角色')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='上级经理')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.account')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'accounts_user',
                'indexes': [models.Index(fields=['account', 'is_active'], name='accounts_us_account_e64813_idx'), models.Index(fields=['feishu_open_id'], name='accounts_us_feishu__fbc20c_idx'), models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'), models.Index(fields=['manager'], name='accounts_us_manager_bb7da4_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
