# Generated by Django 5.2.10 on 2026-01-27 00:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='商机名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('product_line', models.CharField(choices=[('ip_guard', 'IP-Guard'), ('anybackup', 'AnyBackup'), ('anyshare', 'AnyShare'), ('bundle', '套餐'), ('other', '其他')], default='other', max_length=20, verbose_name='产品线')),
                ('stage', models.CharField(choices=[('prospecting', '探索'), ('qualification', '资格确认'), ('proposal', '方案'), ('negotiation', '谈判'), ('closed_won', '赢单'), ('closed_lost', '输单'), ('on_hold', '搁置')], default='prospecting', max_length=20, verbose_name='阶段')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预计金额')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实际金额')),
                ('probability', models.IntegerField(default=0, verbose_name='成交概率(%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='预计成交日期')),
                ('actual_close_date', models.DateField(blank=True, null=True, verbose_name='实际成交日期')),
                ('source_tracking_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='来源追踪ID')),
                ('competitors', models.JSONField(blank=True, default=list, verbose_name='竞争对手')),
                ('competitive_advantage', models.TextField(blank=True, null=True, verbose_name='竞争优势')),
                ('loss_reason', models.CharField(blank=True, choices=[('price', '价格'), ('competitor', '竞争对手'), ('timing', '时机'), ('no_budget', '无预算'), ('no_decision', '无法决策'), ('other', '其他')], max_length=20, null=True, verbose_name='输单原因')),
                ('loss_detail', models.TextField(blank=True, null=True, verbose_name='输单详情')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('converted_from_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_opportunities', to='customers.lead', verbose_name='转化线索')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='customers.customer', verbose_name='客户')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='团队成员')),
            ],
            options={
                'verbose_name': '商机',
                'verbose_name_plural': '商机',
                'db_table': 'opportunities_opportunity',
                'indexes': [models.Index(fields=['customer', 'stage'], name='opportuniti_custome_c635eb_idx'), models.Index(fields=['owner', 'stage'], name='opportuniti_owner_i_c1d12e_idx'), models.Index(fields=['stage', 'probability'], name='opportuniti_stage_cd63b7_idx'), models.Index(fields=['amount'], name='opportuniti_amount_fd153d_idx'), models.Index(fields=['product_line'], name='opportuniti_product_80f355_idx'), models.Index(fields=['expected_close_date'], name='opportuniti_expecte_c56295_idx')],
            },
        ),
    ]
